<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Surfboard;
use Illuminate\Database\Seeder;

class SurfboardDescriptionSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->descriptions() as $slug => $description) {
            Surfboard::query()
                ->where('slug', $slug)
                ->update(['description' => $description]);
        }
    }

    /** @return array<string, string> */
    private function descriptions(): array
    {
        return [
            'tabla-superseed-01' => 'La Tabla Superseed 01 es una hardboard de altas prestaciones pensada para surfistas que buscan rendimiento puro. Su construccion en epoxy combina ligereza y rigidez para generar velocidad inmediata en la pared de la ola y una respuesta precisa en cada giro. El rocker equilibrado facilita las entradas tempranas sin penalizar la maniobrabilidad, mientras que el outline afinado en los cantos aporta agarre y control en condiciones potentes. Ideal para olas de tamano pequeno a mediano con buena forma, ofrece estabilidad direccional y reactividad. Una tabla versatil para progresar hacia un surf mas radical, fluido y comprometido en cada sesion de agua.',
            'tabla-superseed-02' => 'La Tabla Superseed 02 es una softboard disenada para que la iniciacion al surf sea segura, divertida y sin frustraciones. Su nucleo de espuma de alta flotabilidad y la cubierta antideslizante proporcionan una estabilidad excepcional, perfecta para los primeros remontes y para coger las primeras espumas de pie. El volumen generoso ayuda a remar con facilidad y a mantener el equilibrio mientras asimilas la tecnica basica. Las quillas blandas reducen el riesgo de golpes, haciendola idonea para escuelas, ninos y adultos principiantes. Robusta, noble y muy tolerante, acompana tu progresion desde la arena hasta tus primeras olas con total confianza.',
            'tabla-superseed-03' => 'La Tabla Superseed 03 es una hardboard equilibrada que conecta la fase de progresion con el surf de rendimiento. Su perfil en epoxy ofrece flotabilidad suficiente para remar con soltura y, a la vez, la nerviosidad necesaria para empezar a dibujar trazados mas verticales. El rocker moderado permite remadas eficientes y salidas rapidas, mientras que los cantos trabajados aportan agarre en la pared. Funciona especialmente bien en olas pequenas y medianas de fondo de arena, donde su versatilidad brilla. Pensada para surfistas intermedios que quieren ganar fluidez, velocidad y confianza, es una companera fiable para sesiones largas y muy divertidas.',
            'tabla-superseed-04' => 'La Tabla Superseed 04 es una softboard versatil que combina la seguridad de la espuma con un comportamiento mas dinamico. Mantiene una gran flotabilidad para facilitar la remada y los primeros giros, pero su shape algo mas afinado permite empezar a maniobrar y a deslizar por la pared de la ola. Es la eleccion perfecta para quienes ya dominan las espumas y quieren dar el salto a olas verdes sin renunciar a la estabilidad. Su construccion resistente soporta el uso intensivo de escuela y alquiler. Noble, divertida y muy progresiva, te ayuda a consolidar la tecnica mientras disfrutas de cada sesion.',
            'tabla-superseed-05' => 'La Tabla Superseed 05 es una hardboard de corte clasico-funcional, orientada a un surf fluido y elegante. Su construccion en epoxy y su distribucion de volumen equilibrada ofrecen remada potente y planeo temprano, ideales para aprovechar olas con poca fuerza. El outline generoso aporta estabilidad y permite enlazar maniobras con suavidad, mientras que la cola facilita giros amplios y controlados. Es perfecta para surfistas intermedios que disfrutan del ritmo y la conexion con la ola mas que de la radicalidad. Polivalente en una amplia gama de condiciones, se convierte en una tabla de uso diario fiable, predecible y muy gratificante.',
            'tabla-superseed-06' => 'La Tabla Superseed 06 es una softboard pensada para disfrutar del surf desde el primer dia. Su nucleo de espuma y su amplia superficie garantizan flotabilidad y estabilidad, claves para remar sin esfuerzo y ponerse de pie con facilidad. La cubierta texturizada ofrece un agarre seguro incluso con el pie mojado, y sus quillas blandas minimizan los riesgos en el agua. Es la opcion ideal para familias, escuelas y aventureros que buscan diversion inmediata sin complicaciones. Resistente a golpes y muy facil de manejar dentro y fuera del agua, te permite acumular olas y sonrisas mientras desarrollas tus habilidades basicas.',
            'tabla-superseed-07' => 'La Tabla Superseed 07 es una hardboard reactiva disenada para surfistas que ya buscan velocidad y proyeccion. Su construccion ligera en epoxy y su rocker mas pronunciado favorecen un surf vertical, con entradas criticas y giros explosivos en la zona de poder de la ola. Los cantos afilados aumentan el agarre en las paredes empinadas, mientras que la cola estrecha aporta control en condiciones mas exigentes. Funciona mejor en olas con fuerza y buena forma, donde su caracter nervioso se transforma en rendimiento puro. Para quienes quieren llevar su surf un paso mas alla, es una herramienta precisa, exigente y gratificante.',
            'tabla-superseed-08' => 'La Tabla Superseed 08 es una softboard equilibrada que prioriza la diversion y la facilidad de uso. Su gran flotabilidad y su shape estable la convierten en una aliada perfecta para principiantes que quieren progresar con seguridad, asi como para surfistas con experiencia que buscan sesiones relajadas y olas faciles. La espuma de alta densidad ofrece durabilidad y un tacto agradable, mientras que la cubierta antideslizante garantiza un buen posicionamiento. Ideal para dias pequenos y para compartir olas en familia, combina nobleza, resistencia y un comportamiento muy predecible. Una tabla todoterreno para acumular tiempo en el agua sin preocupaciones.',
            'tabla-superseed-09' => 'La Tabla Superseed 09 es una hardboard versatil concebida para rendir en condiciones cambiantes. Su construccion en epoxy aporta ligereza y reactividad, mientras que su volumen bien distribuido garantiza una remada eficiente y un planeo temprano. El shape equilibrado permite tanto trazados largos y fluidos como maniobras mas cerradas, adaptandose al estado de la mar y al nivel del surfista. Destaca en olas pequenas a medianas, donde su polivalencia marca la diferencia. Pensada para intermedios y avanzados que valoran una sola tabla capaz de hacerlo casi todo, ofrece control, velocidad y diversion sesion tras sesion, convirtiendose pronto en tu favorita.',
            'tabla-superseed-10' => 'La Tabla Superseed 10 es una softboard disenada para iniciarte en el surf con la maxima estabilidad. Su generoso volumen y su amplia plataforma facilitan la remada y los primeros remontes, ayudandote a ponerte de pie rapidamente y a mantener el equilibrio. La construccion en espuma resistente absorbe golpes y soporta el uso continuado de escuelas y alquileres. Las quillas blandas hacen que sea segura para todos los publicos, incluidos los mas pequenos. Noble, flotadora y muy tolerante con los errores, es la companera ideal para tus primeras olas y para disfrutar del mar sin presion mientras construyes tu tecnica.',
            'tabla-superseed-11' => 'La Tabla Superseed 11 es una hardboard de rendimiento orientada a un surf moderno y dinamico. Su perfil ligero en epoxy y su rocker progresivo permiten encarar secciones criticas con velocidad y soltura, facilitando giros potentes y aereos en olas con fuerza. La distribucion de volumen concentrada y los cantos afinados ofrecen agarre y respuesta inmediata ante cada apoyo. Es una tabla exigente que recompensa la tecnica depurada y el compromiso en el agua. Pensada para surfistas avanzados que buscan exprimir cada ola, combina precision, reactividad y caracter competitivo, convirtiendose en una herramienta de alto nivel para sesiones intensas y radicales.',
            'tabla-superseed-12' => 'La Tabla Superseed 12 es una softboard polivalente que une seguridad y progresion en una sola tabla. Su flotabilidad elevada facilita coger olas con facilidad, mientras que su shape cuidado permite empezar a deslizar por la pared y ensayar los primeros giros con control. La cubierta antideslizante y la construccion robusta la hacen ideal tanto para principiantes como para surfistas intermedios que buscan diversion sin complicaciones. Funciona estupendamente en olas pequenas y blandas, donde su nobleza brilla. Resistente, estable y muy divertida, es perfecta para acumular olas, ganar confianza y disfrutar del surf en cualquier sesion, sin importar tu nivel.',
            'tabla-superseed-13' => 'La Tabla Superseed 13 es una hardboard equilibrada que combina flotabilidad y rendimiento para un surf fluido y constante. Su construccion en epoxy ofrece ligereza y durabilidad, mientras que su volumen optimizado garantiza remadas potentes y planeo temprano incluso en olas con poca energia. El outline armonico permite enlazar maniobras con suavidad y mantener la velocidad a lo largo de la pared. Es una eleccion excelente para surfistas intermedios que quieren una tabla fiable para el dia a dia. Versatil, predecible y muy agradable de surfear, se adapta a una amplia variedad de condiciones y te ayuda a disfrutar cada salida al mar.',
            'tabla-superseed-14' => 'La Tabla Superseed 14 es una softboard pensada para que el aprendizaje del surf sea sencillo y seguro. Su amplio volumen y su plataforma estable facilitan la remada, los remontes y la puesta de pie, claves en las primeras etapas. La espuma de alta resistencia soporta el uso intensivo y absorbe los impactos, mientras que las quillas blandas aportan seguridad para todos los publicos. Es ideal para escuelas, familias y principiantes que buscan diversion inmediata sin riesgos. Noble, flotadora y muy tolerante, te acompana desde tus primeras espumas hasta tus primeras olas verdes, ayudandote a progresar con confianza en cada sesion.',
        ];
    }
}